<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $catMap = Category::pluck('id', 'slug');

        $products = [
            [
                'id' => 1, 'name' => 'Silk Draped Maxi Dress', 'category' => 'women', 'subcategory' => 'Dresses',
                'price' => 189, 'original_price' => null, 'badge' => 'NEW', 'rating' => 4.5, 'reviews' => 128,
                'color1' => '#f3e8ff', 'color2' => '#fce7f3', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#c084fc',
                'in_stock' => true,
                'colors' => [['name' => 'Lavender', 'hex' => '#c4b5fd'], ['name' => 'Blush', 'hex' => '#fca5a5'], ['name' => 'Slate', 'hex' => '#94a3b8']],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'description' => 'Effortlessly elegant, this fluid silk maxi dress features a sculptural draped silhouette that moves beautifully with every step. Crafted from 100% pure silk with a self-tie waist belt, it transitions seamlessly from garden parties to evening galas.',
                'details' => ['100% Pure Silk', 'Self-tie waist belt', 'Side split hem', 'V-neckline', 'Regular fit'],
                'care' => 'Dry clean only. Do not bleach. Cool iron if needed.',
                'fit' => 'True to size. Model is 5\'9" wearing size S.', 'sku' => 'LXW-001',
                'tags' => ['silk', 'maxi', 'dress', 'formal', 'evening', 'draped'], 'related_ids' => [7, 18, 9, 4],
            ],
            [
                'id' => 2, 'name' => 'Oxford Slim-Fit Blazer', 'category' => 'men', 'subcategory' => 'Blazers',
                'price' => 295, 'original_price' => null, 'badge' => 'BESTSELLER', 'rating' => 5.0, 'reviews' => 87,
                'color1' => '#dbeafe', 'color2' => '#e0e7ff', 'icon_class' => 'fas fa-user-tie', 'icon_color' => '#93c5fd',
                'in_stock' => true,
                'colors' => [['name' => 'Midnight', 'hex' => '#1e293b'], ['name' => 'Navy', 'hex' => '#1e3a5f'], ['name' => 'Camel', 'hex' => '#b08050']],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'description' => 'Precision-tailored in our signature Oxford weave, this slim-fit blazer is the cornerstone of a refined wardrobe.',
                'details' => ['Oxford weave wool blend', 'Slim fit', 'Peak lapel', '2-button fastening', 'Functional sleeve buttons'],
                'care' => 'Dry clean only.', 'fit' => 'Slim fit. Size up if between sizes.', 'sku' => 'LXM-002',
                'tags' => ['blazer', 'oxford', 'slim', 'formal', 'suit'], 'related_ids' => [11, 13, 16, 6],
            ],
            [
                'id' => 3, 'name' => 'Structured Leather Tote', 'category' => 'accessories', 'subcategory' => 'Bags',
                'price' => 145, 'original_price' => 192, 'badge' => 'SALE', 'rating' => 4.0, 'reviews' => 204,
                'color1' => '#fef3c7', 'color2' => '#fed7aa', 'icon_class' => 'fas fa-shopping-bag', 'icon_color' => '#fbbf24',
                'in_stock' => true,
                'colors' => [['name' => 'Tan', 'hex' => '#b08050'], ['name' => 'Black', 'hex' => '#1a1a1a'], ['name' => 'Ivory', 'hex' => '#f5f0e8']],
                'sizes' => ['One Size'],
                'description' => 'A modern classic, this structured tote in premium full-grain leather develops a beautiful patina over time.',
                'details' => ['Full-grain leather', 'Magnetic snap closure', 'Zip interior pocket', 'Detachable shoulder strap', 'Brass hardware'],
                'care' => 'Wipe with damp cloth. Condition with leather cream.', 'fit' => 'Dimensions: 35 × 28 × 12 cm', 'sku' => 'LXA-003',
                'tags' => ['tote', 'leather', 'bag', 'handbag'], 'related_ids' => [10, 20, 5, 17],
            ],
            [
                'id' => 4, 'name' => 'Cashmere Wrap Coat', 'category' => 'women', 'subcategory' => 'Coats',
                'price' => 420, 'original_price' => null, 'badge' => 'TRENDING', 'rating' => 5.0, 'reviews' => 56,
                'color1' => '#f5f5f4', 'color2' => '#e7e5e4', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#a8a29e',
                'in_stock' => true,
                'colors' => [['name' => 'Oatmeal', 'hex' => '#d6c9b0'], ['name' => 'Charcoal', 'hex' => '#374151'], ['name' => 'Bordeaux', 'hex' => '#7f1d1d']],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'description' => 'Indulge in unparalleled warmth and softness with this luxurious wrap coat crafted from 100% Grade A Mongolian cashmere.',
                'details' => ['100% Grade A Cashmere', 'Wrap silhouette', 'Oversized lapels', 'Self-tie belt', 'Lined in silk crepe'],
                'care' => 'Hand wash cold or dry clean.', 'fit' => 'Relaxed wrap fit. Model wears XS/S.', 'sku' => 'LXW-004',
                'tags' => ['cashmere', 'coat', 'wrap', 'luxury', 'winter'], 'related_ids' => [1, 9, 15, 7],
            ],
            [
                'id' => 5, 'name' => 'Diamond Tennis Bracelet', 'category' => 'accessories', 'subcategory' => 'Jewellery',
                'price' => 860, 'original_price' => null, 'badge' => 'LIMITED', 'rating' => 5.0, 'reviews' => 32,
                'color1' => '#e0f2fe', 'color2' => '#f0fdf4', 'icon_class' => 'fas fa-gem', 'icon_color' => '#38bdf8',
                'in_stock' => true,
                'colors' => [['name' => 'White Gold', 'hex' => '#e8e8e8'], ['name' => 'Yellow Gold', 'hex' => '#fbbf24'], ['name' => 'Rose Gold', 'hex' => '#e879a0']],
                'sizes' => ['15cm', '17cm', '19cm'],
                'description' => 'A timeless symbol of sophistication, this tennis bracelet features 36 brilliant-cut diamonds set in a continuous line.',
                'details' => ['0.72 total carat weight', 'VS1-VS2 clarity', 'G-H color grade', 'Secure box clasp with safety', 'Available in 3 lengths'],
                'care' => 'Professional clean annually. Store in provided pouch.', 'fit' => 'Measure wrist circumference, add 1cm for comfort.', 'sku' => 'LXA-005',
                'tags' => ['diamond', 'bracelet', 'tennis', 'jewellery', 'luxury', 'gold'], 'related_ids' => [14, 17, 10, 8],
            ],
            [
                'id' => 6, 'name' => 'Leather Chelsea Boots', 'category' => 'men', 'subcategory' => 'Shoes',
                'price' => 245, 'original_price' => 289, 'badge' => 'SALE', 'rating' => 4.5, 'reviews' => 164,
                'color1' => '#d4b8a0', 'color2' => '#c4a882', 'icon_class' => 'fas fa-shoe-prints', 'icon_color' => '#92400e',
                'in_stock' => true,
                'colors' => [['name' => 'Brown', 'hex' => '#7c4c2a'], ['name' => 'Black', 'hex' => '#1a1a1a']],
                'sizes' => ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
                'description' => 'Handcrafted in Spain from premium calfskin leather, these Chelsea boots feature a classic elastic side panel and a subtle Cuban heel.',
                'details' => ['Premium calfskin leather upper', 'Goodyear welt construction', 'Elastic side panel', 'Leather sole', 'Cuban heel 3.5cm'],
                'care' => 'Polish regularly with matching shoe cream.', 'fit' => 'True to UK size. Half sizes round up.', 'sku' => 'LXM-006',
                'tags' => ['chelsea', 'boots', 'leather', 'men', 'shoes'], 'related_ids' => [13, 2, 19, 16],
            ],
            [
                'id' => 7, 'name' => 'Floral Midi Skirt', 'category' => 'women', 'subcategory' => 'Skirts',
                'price' => 89, 'original_price' => null, 'badge' => 'NEW', 'rating' => 4.0, 'reviews' => 89,
                'color1' => '#fce7f3', 'color2' => '#fee2e2', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#f472b6',
                'in_stock' => true,
                'colors' => [['name' => 'Floral Rose', 'hex' => '#fda4af'], ['name' => 'Floral Blue', 'hex' => '#93c5fd'], ['name' => 'Floral Ivory', 'hex' => '#fef9c3']],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'description' => 'This effortlessly feminine midi skirt features a hand-painted floral print on flowing chiffon.',
                'details' => ['100% Chiffon', 'Elasticated waistband', 'Midi length', 'Fully lined', 'Hand-painted print'],
                'care' => 'Machine wash cold, gentle cycle.', 'fit' => 'True to size. Sits at natural waist.', 'sku' => 'LXW-007',
                'tags' => ['floral', 'midi', 'skirt', 'feminine', 'chiffon'], 'related_ids' => [1, 4, 9, 18],
            ],
            [
                'id' => 8, 'name' => 'Minimalist Swiss Watch', 'category' => 'accessories', 'subcategory' => 'Watches',
                'price' => 320, 'original_price' => null, 'badge' => 'BESTSELLER', 'rating' => 5.0, 'reviews' => 310,
                'color1' => '#f1f5f9', 'color2' => '#e2e8f0', 'icon_class' => 'fas fa-clock', 'icon_color' => '#64748b',
                'in_stock' => true,
                'colors' => [['name' => 'Silver', 'hex' => '#c0c0c0'], ['name' => 'Gold', 'hex' => '#fbbf24'], ['name' => 'Black', 'hex' => '#1a1a1a']],
                'sizes' => ['36mm', '40mm'],
                'description' => 'The epitome of Swiss precision and minimal design, this watch features a sapphire crystal glass and a Swiss-made automatic movement.',
                'details' => ['Swiss automatic movement', 'Sapphire crystal glass', '100m water resistant', '316L stainless steel case', 'Italian leather strap'],
                'care' => 'Service every 5 years. Avoid magnets.', 'fit' => 'Available in 36mm and 40mm case diameter.', 'sku' => 'LXA-008',
                'tags' => ['watch', 'swiss', 'minimalist', 'automatic', 'luxury'], 'related_ids' => [5, 14, 17, 3],
            ],
            [
                'id' => 9, 'name' => 'Relaxed Linen Blazer', 'category' => 'women', 'subcategory' => 'Blazers',
                'price' => 165, 'original_price' => null, 'badge' => 'NEW', 'rating' => 4.0, 'reviews' => 14,
                'color1' => '#d1fae5', 'color2' => '#a7f3d0', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#34d399',
                'in_stock' => true,
                'colors' => [['name' => 'Sage', 'hex' => '#86efac'], ['name' => 'Sand', 'hex' => '#e5d0a8'], ['name' => 'White', 'hex' => '#f8f8f8']],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'description' => 'A wardrobe hero for the modern woman, this relaxed linen blazer can be dressed up or down effortlessly.',
                'details' => ['100% Belgian Linen', 'Relaxed fit', 'Single button fastening', 'Patch pockets', 'Fully lined'],
                'care' => 'Machine wash 30°C. Iron while damp.', 'fit' => 'Oversized fit. Size down for structured look.', 'sku' => 'LXW-009',
                'tags' => ['linen', 'blazer', 'relaxed', 'women', 'summer'], 'related_ids' => [1, 4, 15, 7],
            ],
            [
                'id' => 10, 'name' => 'Printed Silk Scarf', 'category' => 'accessories', 'subcategory' => 'Scarves',
                'price' => 75, 'original_price' => null, 'badge' => 'NEW', 'rating' => 5.0, 'reviews' => 7,
                'color1' => '#fef3c7', 'color2' => '#fde68a', 'icon_class' => 'fas fa-scroll', 'icon_color' => '#f59e0b',
                'in_stock' => true,
                'colors' => [['name' => 'Amber', 'hex' => '#f59e0b'], ['name' => 'Cobalt', 'hex' => '#3b82f6'], ['name' => 'Emerald', 'hex' => '#10b981']],
                'sizes' => ['70×70cm', '90×90cm'],
                'description' => 'A vibrant hand-printed silk scarf featuring an original abstract design inspired by modernist art.',
                'details' => ['100% Habotai Silk', 'Hand-rolled edges', 'Original print design', 'Two sizes available', 'Gift-boxed'],
                'care' => 'Hand wash cold or dry clean.', 'fit' => '70×70cm or 90×90cm square.', 'sku' => 'LXA-010',
                'tags' => ['scarf', 'silk', 'printed', 'accessories'], 'related_ids' => [5, 14, 3, 8],
            ],
            [
                'id' => 11, 'name' => 'Merino Knit Polo', 'category' => 'men', 'subcategory' => 'Tops',
                'price' => 120, 'original_price' => null, 'badge' => 'NEW', 'rating' => 4.0, 'reviews' => 22,
                'color1' => '#ccfbf1', 'color2' => '#99f6e4', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#2dd4bf',
                'in_stock' => true,
                'colors' => [['name' => 'Teal', 'hex' => '#14b8a6'], ['name' => 'Navy', 'hex' => '#1e3a5f'], ['name' => 'Cream', 'hex' => '#faf0e0']],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'description' => 'Knitted in Italy from extra-fine Merino wool, this polo shirt offers the perfect balance of sophistication and comfort.',
                'details' => ['Extra-fine Merino wool', 'Piqué-knit texture', '3-button placket', 'Ribbed collar and cuffs', 'Regular fit'],
                'care' => 'Machine wash 30°C wool cycle.', 'fit' => 'Regular fit. True to size.', 'sku' => 'LXM-011',
                'tags' => ['merino', 'polo', 'knit', 'men', 'top'], 'related_ids' => [2, 16, 13, 6],
            ],
            [
                'id' => 12, 'name' => 'Suede Ankle Boots', 'category' => 'women', 'subcategory' => 'Shoes',
                'price' => 210, 'original_price' => null, 'badge' => 'NEW', 'rating' => 5.0, 'reviews' => 5,
                'color1' => '#ede9fe', 'color2' => '#ddd6fe', 'icon_class' => 'fas fa-shoe-prints', 'icon_color' => '#8b5cf6',
                'in_stock' => true,
                'colors' => [['name' => 'Plum', 'hex' => '#7c3aed'], ['name' => 'Tan', 'hex' => '#a87050'], ['name' => 'Black', 'hex' => '#1a1a1a']],
                'sizes' => ['EU 35', 'EU 36', 'EU 37', 'EU 38', 'EU 39', 'EU 40', 'EU 41'],
                'description' => 'These suede ankle boots with a block heel are the season\'s most versatile footwear.',
                'details' => ['Premium suede upper', 'Padded insole', 'Side zip fastening', 'Stacked block heel 6cm', 'Leather lining'],
                'care' => 'Protect with suede spray before first wear.', 'fit' => 'True to EU size.', 'sku' => 'LXW-012',
                'tags' => ['suede', 'ankle', 'boots', 'block heel', 'women', 'shoes'], 'related_ids' => [7, 1, 4, 9],
            ],
            [
                'id' => 13, 'name' => 'Slim-Fit Chinos', 'category' => 'men', 'subcategory' => 'Trousers',
                'price' => 95, 'original_price' => null, 'badge' => null, 'rating' => 4.0, 'reviews' => 145,
                'color1' => '#fef9c3', 'color2' => '#fde68a', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#ca8a04',
                'in_stock' => true,
                'colors' => [['name' => 'Khaki', 'hex' => '#c8b070'], ['name' => 'Navy', 'hex' => '#1e3a5f'], ['name' => 'Olive', 'hex' => '#6b7c35'], ['name' => 'Stone', 'hex' => '#c4b89a']],
                'sizes' => ['28×30', '30×30', '30×32', '32×30', '32×32', '34×32', '36×32'],
                'description' => 'The definitive smart-casual trouser, these slim-fit chinos are cut from a stretch-cotton blend for all-day comfort.',
                'details' => ['98% Cotton, 2% Elastane', 'Slim fit', '5-pocket design', 'Zip fly', 'Machine washable'],
                'care' => 'Machine wash 40°C. Tumble dry low.', 'fit' => 'Slim fit through thigh and leg.', 'sku' => 'LXM-013',
                'tags' => ['chinos', 'slim', 'trousers', 'men', 'smart casual'], 'related_ids' => [6, 2, 11, 16],
            ],
            [
                'id' => 14, 'name' => 'Pearl Drop Earrings', 'category' => 'accessories', 'subcategory' => 'Jewellery',
                'price' => 145, 'original_price' => null, 'badge' => 'NEW', 'rating' => 5.0, 'reviews' => 18,
                'color1' => '#f0fdf4', 'color2' => '#dcfce7', 'icon_class' => 'fas fa-gem', 'icon_color' => '#4ade80',
                'in_stock' => true,
                'colors' => [['name' => 'White Pearl', 'hex' => '#f8f5f0'], ['name' => 'Black Pearl', 'hex' => '#2d2d2d']],
                'sizes' => ['One Size'],
                'description' => 'Timeless and refined, these drop earrings feature lustrous freshwater pearls suspended from delicate 18ct gold vermeil chains.',
                'details' => ['Freshwater pearl', '18ct gold vermeil', 'Sterling silver posts', '4.5cm drop length', 'Gift-boxed'],
                'care' => 'Avoid perfume and water contact.', 'fit' => 'Drop length: 4.5cm from ear.', 'sku' => 'LXA-014',
                'tags' => ['pearl', 'earrings', 'drop', 'jewellery', 'gold'], 'related_ids' => [5, 17, 10, 8],
            ],
            [
                'id' => 15, 'name' => 'Oversized Wool Sweater', 'category' => 'women', 'subcategory' => 'Knitwear',
                'price' => 185, 'original_price' => null, 'badge' => 'TRENDING', 'rating' => 4.5, 'reviews' => 73,
                'color1' => '#fdf4ff', 'color2' => '#fae8ff', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#d946ef',
                'in_stock' => true,
                'colors' => [['name' => 'Lilac', 'hex' => '#c084fc'], ['name' => 'Cream', 'hex' => '#faf0e0'], ['name' => 'Chocolate', 'hex' => '#5c3d2e']],
                'sizes' => ['XS/S', 'M/L', 'XL/XXL'],
                'description' => 'Cosy, chic, and endlessly wearable, this oversized sweater in a ribbed merino-wool blend.',
                'details' => ['70% Merino, 30% Nylon', 'Oversized fit', 'Ribbed texture', 'Dropped shoulder', 'Cropped sleeves'],
                'care' => 'Hand wash cold. Lay flat to dry.', 'fit' => 'Oversized. Model wears XS/S.', 'sku' => 'LXW-015',
                'tags' => ['wool', 'sweater', 'oversized', 'knitwear', 'women', 'cosy'], 'related_ids' => [4, 9, 7, 1],
            ],
            [
                'id' => 16, 'name' => 'Classic Oxford Shirt', 'category' => 'men', 'subcategory' => 'Shirts',
                'price' => 110, 'original_price' => null, 'badge' => 'BESTSELLER', 'rating' => 4.5, 'reviews' => 198,
                'color1' => '#eff6ff', 'color2' => '#dbeafe', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#60a5fa',
                'in_stock' => true,
                'colors' => [['name' => 'White', 'hex' => '#f8f8f8'], ['name' => 'Blue', 'hex' => '#93c5fd'], ['name' => 'Pink', 'hex' => '#fca5a5']],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'description' => 'A wardrobe staple reinvented. Our Oxford shirt is woven from premium two-ply cotton in a classic basket weave.',
                'details' => ['100% 2-ply Oxford cotton', 'Button-down collar', 'Chest pocket', 'Regular fit', 'Machine washable'],
                'care' => 'Machine wash 40°C. Iron while damp for best results.', 'fit' => 'Regular fit. True to size.', 'sku' => 'LXM-016',
                'tags' => ['oxford', 'shirt', 'classic', 'men', 'formal'], 'related_ids' => [2, 11, 13, 19],
            ],
            [
                'id' => 17, 'name' => 'Geometric Gold Necklace', 'category' => 'accessories', 'subcategory' => 'Jewellery',
                'price' => 220, 'original_price' => null, 'badge' => 'NEW', 'rating' => 4.5, 'reviews' => 27,
                'color1' => '#fefce8', 'color2' => '#fef9c3', 'icon_class' => 'fas fa-gem', 'icon_color' => '#eab308',
                'in_stock' => true,
                'colors' => [['name' => 'Yellow Gold', 'hex' => '#fbbf24'], ['name' => 'Rose Gold', 'hex' => '#e879a0'], ['name' => 'Silver', 'hex' => '#c0c0c0']],
                'sizes' => ['40cm', '45cm', '50cm'],
                'description' => 'A sculptural statement piece, this geometric pendant necklace is handcrafted by artisans in Florence.',
                'details' => ['18ct gold vermeil', 'Sterling silver base', 'Hexagonal pendant', 'Adjustable 40-50cm chain', 'Lobster clasp'],
                'care' => 'Store in pouch when not wearing. Avoid chlorine.', 'fit' => 'Chain adjustable from 40cm to 50cm.', 'sku' => 'LXA-017',
                'tags' => ['necklace', 'gold', 'geometric', 'jewellery', 'pendant'], 'related_ids' => [14, 5, 10, 3],
            ],
            [
                'id' => 18, 'name' => 'Satin Slip Dress', 'category' => 'women', 'subcategory' => 'Dresses',
                'price' => 135, 'original_price' => 170, 'badge' => 'SALE', 'rating' => 4.5, 'reviews' => 93,
                'color1' => '#fdf2f8', 'color2' => '#fce7f3', 'icon_class' => 'fas fa-tshirt', 'icon_color' => '#ec4899',
                'in_stock' => true,
                'colors' => [['name' => 'Champagne', 'hex' => '#f5e6c8'], ['name' => 'Black', 'hex' => '#1a1a1a'], ['name' => 'Dusty Rose', 'hex' => '#d4a0a0']],
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'description' => 'Channel effortless 90s glamour in this satin slip dress. Cut on the bias for a silhouette that skims the body flatteringly.',
                'details' => ['100% Acetate satin', 'Bias cut', 'Adjustable spaghetti straps', 'Lace-trimmed hem', 'Midi length'],
                'care' => 'Hand wash cold. Do not wring.', 'fit' => 'Slim cut. Size up for a more relaxed fit.', 'sku' => 'LXW-018',
                'tags' => ['satin', 'slip', 'dress', 'midi', 'elegant'], 'related_ids' => [1, 7, 4, 12],
            ],
            [
                'id' => 19, 'name' => 'Braided Leather Belt', 'category' => 'men', 'subcategory' => 'Accessories',
                'price' => 65, 'original_price' => null, 'badge' => null, 'rating' => 4.5, 'reviews' => 89,
                'color1' => '#fef3c7', 'color2' => '#fde68a', 'icon_class' => 'fas fa-grip-lines', 'icon_color' => '#d97706',
                'in_stock' => true,
                'colors' => [['name' => 'Brown', 'hex' => '#7c4c2a'], ['name' => 'Black', 'hex' => '#1a1a1a'], ['name' => 'Tan', 'hex' => '#c8a070']],
                'sizes' => ['S (75-85cm)', 'M (85-95cm)', 'L (95-105cm)', 'XL (105-115cm)'],
                'description' => 'Hand-braided in Florence from three strands of premium full-grain leather, this belt develops a rich patina with every wear.',
                'details' => ['Full-grain leather', 'Hand-braided construction', 'Solid brass roller buckle', '3.5cm width', 'Made in Italy'],
                'care' => 'Condition with leather balm occasionally.', 'fit' => 'Measure your waist, not trouser size.', 'sku' => 'LXM-019',
                'tags' => ['belt', 'leather', 'braided', 'men', 'accessories'], 'related_ids' => [6, 13, 2, 16],
            ],
            [
                'id' => 20, 'name' => 'Velvet Evening Bag', 'category' => 'accessories', 'subcategory' => 'Bags',
                'price' => 195, 'original_price' => null, 'badge' => 'LIMITED', 'rating' => 5.0, 'reviews' => 24,
                'color1' => '#f5f3ff', 'color2' => '#ede9fe', 'icon_class' => 'fas fa-shopping-bag', 'icon_color' => '#8b5cf6',
                'in_stock' => false,
                'colors' => [['name' => 'Amethyst', 'hex' => '#7c3aed'], ['name' => 'Emerald', 'hex' => '#059669'], ['name' => 'Burgundy', 'hex' => '#9f1239']],
                'sizes' => ['One Size'],
                'description' => 'Make an entrance with this jewel-toned velvet clutch. The lustrous crushed velvet is adorned with a vintage-inspired gold-tone twist lock clasp.',
                'details' => ['Crushed velvet exterior', 'Gold-tone hardware', 'Twist lock clasp', 'Slip interior pocket', 'Detachable chain strap'],
                'care' => 'Spot clean only. Store in dust bag.', 'fit' => 'Dimensions: 22 × 13 × 5 cm', 'sku' => 'LXA-020',
                'tags' => ['velvet', 'clutch', 'evening', 'bag', 'luxury'], 'related_ids' => [3, 10, 5, 14],
            ],
        ];

        foreach ($products as $p) {
            Product::updateOrCreate(
                ['sku' => $p['sku']],
                [
                    'name'           => $p['name'],
                    'slug'           => Str::slug($p['name']),
                    'sku'            => $p['sku'],
                    'category_id'    => $catMap[$p['category']],
                    'subcategory'    => $p['subcategory'],
                    'price'          => $p['price'],
                    'original_price' => $p['original_price'],
                    'badge'          => $p['badge'],
                    'rating'         => $p['rating'],
                    'reviews'        => $p['reviews'],
                    'color1'         => $p['color1'],
                    'color2'         => $p['color2'],
                    'icon_class'     => $p['icon_class'],
                    'icon_color'     => $p['icon_color'],
                    'in_stock'       => $p['in_stock'],
                    'colors'         => $p['colors'],
                    'sizes'          => $p['sizes'],
                    'description'    => $p['description'],
                    'details'        => $p['details'],
                    'care'           => $p['care'],
                    'fit'            => $p['fit'],
                    'tags'           => $p['tags'],
                    'related_ids'    => $p['related_ids'],
                ]
            );
        }
    }
}
